### PR TITLE
Fix inconsistent args with FeatureLayerMetadata.create and QueryFields.create

### LINKED ISSUE #240: Layers metadata returning same id for every layer
When creating the layers list here:
https://github.com/koopjs/FeatureServer/blob/878c38ffd3ec65870a22df0ee209f3015cf8866d/lib/layers-metadata.js#L10-L12

The `create` options specify `layerId` as a direct property of `options`. In the `normalizeInput` function, `layerId` is retrieved from `req.params.layer` which is not what we want given the above.
https://github.com/koopjs/FeatureServer/blob/878c38ffd3ec65870a22df0ee209f3015cf8866d/lib/helpers/table-layer-metadata.js#L27-L32

This causes `layerId` to be `undefined` and each layer is assigned `id: 0`.

### PR DESCRIPTION
**Pull request by schmidtk**
This resolves a couple bugs related to how options are normalized in various parts of the library.

The first is explained in #240, but essentially `FeatureLayerMetadata.create` calls `TableLayerMetadata.normalizeInput` with inconsistent options. The normalize call expects the `layerId` to be under `req.params.layer` (this is the case when making a layer request), but when requesting layers metadata from the `/layers` endpoint the layerId is under `req.layerId`.

https://github.com/koopjs/FeatureServer/blob/878c38ffd3ec65870a22df0ee209f3015cf8866d/lib/helpers/table-layer-metadata.js#L27-L32

https://github.com/koopjs/FeatureServer/blob/878c38ffd3ec65870a22df0ee209f3015cf8866d/lib/layers-metadata.js#L10-L12

The `normalizeOptions` call for QueryFields/Fields does not expect a `data` property. The fields within `data` are expected to be directly in the `inputOptions`.
https://github.com/koopjs/FeatureServer/blob/878c38ffd3ec65870a22df0ee209f3015cf8866d/lib/helpers/fields/fields.js#L10-L20

For the `queryRelatedRecords` case, two input arguments are passed when only one is expected (`inputOptions`).

Resolves #240.

### CODE REVIEW

**Comment by rgwozdz** [comment]
Thanks @schmidtk, much appreciated.  All that is needed is a entry in the CHANGELOG.md under `## Unreleased`.  Once added, I will merge and publish.

**Comment by schmidtk** [comment]
Thanks @rgwozdz, added notes to the changelog. Let me know if you need anything further.

**Review by rgwozdz — APPROVED** [review]
Thanks @schmidtk.

**Comment by rgwozdz** [comment]
published in featureserver@4.0.2

**Pull request merged**
