### PR TITLE
drop type from features array in query response

### PR DESCRIPTION
**Pull request by jgravois**
'type' is a GeoJSON thing

http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Feature_object/02r3000000n8000000

### CODE REVIEW

**Comment by jgravois** [comment]
more info: https://github.com/koopjs/koop-provider-google-sheets/pull/9#issuecomment-329265275

**Comment by dmfenton** [comment]
Still the wrong place, this needs to happen inside Winnow otherwise we're adding an additional loop over all features

**Comment by dmfenton** [comment]
Check out this part of Winnow: https://github.com/koopjs/winnow/blob/master/src/executeQuery.js#L60-L73

**Comment by dmfenton** [comment]
Actually it needs to happen in this code block https://github.com/koopjs/winnow/blob/master/src/select/fields.js#L8-L10

if `options.toEsri` is set, we should not include `type` in the select clause

**Pull request closed without merging**
