### PR TITLE
Pass domain and nullable properties through.

### PR DESCRIPTION
**Pull request by ahamilt**
For layer queries, pass the domain and nullable properties
through if provided.

### CODE REVIEW

**Comment by rgwozdz** [comment]
CI build is failing. Looks like you haven't run `npm test` because the linter is failing and tests haven't run.
Are you using a client that fails in some way due to these missing properties?  I'm just wondering what has prompted your proposed change.
We will need to test this change on all the various ArcGIS clients (Pro, Scene Viewer, Earth, AGO, etc) to ensure it doesn't change behavior or compatability.

**Comment by ahamilt** [comment]
I've fixed the failing test / linter check.

Without the domain, ArcGIS clients can't resolve the values in a field to the associated label. (e.g the standard popup you'd see on an ArcGIS client would should a number instead of the label. Similar with Operations Dashboard widgets etc.)

If the nullable flag is always false, and returned features include null values, some ArcGIS mobile clients will fail to render features on a map. I don't recall if it was apps using the older 10.x runtime, or the newer 100.x runtimes.

**Comment by rgwozdz** [comment]
@ahamilt, this is great.  Will release today.

**Comment by rgwozdz** [comment]
Released in 2.21.2.

**Pull request merged**
